### ISSUE TITLE
Confusing timing for "translation may be missing new information" comment

### ISSUE THREAD

**Issue by cl8n** [TicClick/observatory#25]
as said on discord I just don't understand what happened here at all https://github.com/ppy/osu-wiki/pull/11122#issuecomment-2028962100

**Comment by TicClick** [comment]
more examples:
- https://github.com/ppy/osu-wiki/pull/11298#issuecomment-2091862153
- https://github.com/ppy/osu-wiki/pull/11323#issuecomment-2091902500

**Comment by cl8n** [comment]
https://github.com/ppy/osu-wiki/pull/11430#issuecomment-2179427801
